name:                wilton-ffi
version:             0.1.0.0
github:              "https://github.com/wilton-iot/wilton-ffi"
license:             Apache
author:              "wilton"
maintainer:          "alex@staticlibs.net"
copyright:           "2018 alex at staticlibs.net"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/wilton-iot/wilton-ffi#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring

library:
  source-dirs: src

